import {
  Heart,
  Gem,
  Flower2,
  Users,
  Cake,
  Wine,
  Rocket,
  Briefcase,
  Star,
  Baby,
  Crown,
  Palette,
  Music,
  Settings2,
  HeartHandshake,
  type LucideIcon,
} from "lucide-react";

export const serviceIcons: Record<string, LucideIcon> = {
  weddings: Heart,
  engagements: Gem,
  "bridal-events": Flower2,
  "family-events": Users,
  "kids-birthdays": Cake,
  "luxury-dinners": Wine,
  "product-launches": Rocket,
  "corporate-events": Briefcase,
  "private-events": Star,
  "baby-showers": Baby,
  "gala-luxury-events": Crown,
  "event-styling-decor": Palette,
  "event-entertainment": Music,
  "event-production": Settings2,
  anniversaries: HeartHandshake,
};
